import type { LayerConfig } from '../types';

export const LAYERS: LayerConfig[] = [
  {
    id: 'hotspot',
    name: 'HOTSPOT SIPONGI',
    file: '/data/hotspot_sipongi.json',
    markerType: 'circle',
    color: '#ff5500',
    hasDate: true,
    cluster: true,
    defaultVisible: true,
    popupFields: [
      { key: 'kabkota', label: 'Kab/Kota' },
      { key: 'nama_provinsi', label: 'Provinsi' },
      { key: 'sumber', label: 'Satelit' },
      { key: 'confidence_level', label: 'Confidence' },
      { key: 'date_hotspot', label: 'Tanggal' },
    ],
  },
  {
    id: 'gempa-global',
    name: 'GEMPA (BMKG)',
    file: '/data/3mgempaQL.json',
    markerType: 'circle',
    color: '#e53e3e',
    hasDate: true,
    cluster: true,
    defaultVisible: false,
    popupFields: [
      { key: 'place', label: 'Lokasi' },
      { key: 'mag', label: 'Magnitudo', format: 'magnitude' },
      { key: 'depth', label: 'Kedalaman (km)' },
      { key: 'time', label: 'Waktu' },
    ],
  },
  {
    id: 'gempa-alert',
    name: 'ALERT GEMPA (BMKG)',
    file: '/data/datagempa.json',
    markerType: 'circle',
    color: '#fc4349',
    hasDate: true,
    cluster: false,
    defaultVisible: false,
    popupFields: [
      { key: 'area', label: 'Area' },
      { key: 'magnitude', label: 'Magnitudo', format: 'magnitude' },
      { key: 'depth', label: 'Kedalaman (km)' },
      { key: 'dirasakan', label: 'Dirasakan' },
      { key: 'potential', label: 'Potensi' },
    ],
  },
  {
    id: 'katalog-gempa',
    name: 'KATALOG GEMPA (BMKG)',
    file: '/data/katalog_gempa.json',
    markerType: 'circle',
    color: '#f687b3',
    hasDate: true,
    cluster: true,
    defaultVisible: false,
    popupFields: [
      { key: 'lokasi', label: 'Lokasi' },
      { key: 'mag', label: 'Magnitudo', format: 'magnitude' },
      { key: 'depth', label: 'Kedalaman (km)' },
      { key: 'tsunami', label: 'Tsunami' },
      { key: 'date', label: 'Tanggal' },
    ],
  },
  {
    id: 'gunung-api',
    name: 'GUNUNG API (VSI)',
    file: '/data/vsi-gunung-api.json',
    markerType: 'gif',
    gifSrc: '/icons/erupt2.gif',
    pinImageRules: [
      { field: 'ga_status', value: 1, image: '/icons/no_erupt.png', status: 'LEVEL 1 (Normal)' },
      { field: 'ga_status', value: 2, image: '/icons/erupt2.gif', status: 'LEVEL 2 (Waspada)' },
      { field: 'ga_status', value: 3, image: '/icons/erupt3.gif', status: 'LEVEL 3 (Siaga)' },
      { field: 'ga_status', value: 4, image: '/icons/erupt3.gif', status: 'LEVEL 4 (Awas)' },
    ],
    color: '#f6ad55',
    hasDate: true,
    cluster: false,
    defaultVisible: true,
    popupFields: [
      { key: 'ga_nama_gapi', label: 'Nama' },
      { key: 'ga_prov_gapi', label: 'Provinsi' },
      { key: 'ga_elev_gapi', label: 'Elevasi (m)' },
      { key: 'cu_avcode', label: 'Status' },
      { key: 'volcanic_act_summ', label: 'Aktivitas' },
      { key: 'date_time', label: 'Tanggal' },
    ],
  },
  {
    id: 'vsi-gempa',
    name: 'GEMPA BUMI (VSI)',
    file: '/data/vsi-gempa.json',
    markerType: 'circle',
    color: '#4299e1',
    hasDate: true,
    cluster: true,
    defaultVisible: true,
    popupFields: [
      { key: 'area', label: 'Area' },
      { key: 'magnitude', label: 'Magnitudo', format: 'magnitude' },
      { key: 'depth', label: 'Kedalaman (km)' },
      { key: 'mmi', label: 'MMI' },
      { key: 'nearest_volcano', label: 'Gunung Api Terdekat' },
      { key: 'datetime_wib', label: 'Waktu (WIB)' },
    ],
  },
  {
    id: 'gerakan-tanah',
    name: 'GERAKAN TANAH (VSI)',
    file: '/data/vsi-gerakan-tanah.json',
    markerType: 'gif',
    gifSrc: '/icons/landslide.gif',
    color: '#c05621',
    hasDate: true,
    cluster: false,
    defaultVisible: true,
    popupFields: [
      { key: 'crs_cty', label: 'Kota' },
      { key: 'crs_prv', label: 'Provinsi' },
      { key: 'qls_tgt', label: 'Jenis' },
      { key: 'qls_zkg', label: 'Zona Risiko' },
      { key: 'date', label: 'Tanggal' },
    ],
  },
  {
    id: 'gamma-irrad',
    name: 'GAMMA IRRADIATOR (IAEA)',
    file: '/data/gamma-irradiators.json',
    markerType: 'circle',
    color: '#9b59b6',
    hasDate: false,
    cluster: true,
    defaultVisible: false,
    popupFields: [
      { key: 'city', label: 'Kota' },
      { key: 'country', label: 'Negara' },
    ],
  },
];

export const LAYER_IDS = LAYERS.map((l) => l.id);

export const ALERT_COLORS: Record<string, string> = {
  GREEN: '#38a169',
  YELLOW: '#d69e2e',
  ORANGE: '#dd6b20',
  RED: '#e53e3e',
};
